// ignore_for_file: constant_identifier_names

enum Permission {
  CREATE_USER,
  // Product
  VIEW_PRODUCT, //1
  UPDATE_PRODUCT, //2
  CREATE_PRODUCT, //3
  DELETE_PRODUCT, //4

  // Ingredient
  VIEW_INGREDIENT, //5
  UPDATE_INGREDIENT, //6
  CREATE_INGREDIENT, //7
  DELETE_INGREDIENT, //8

  // Input invoice
  VIEW_INPUT_INVOICE, //9
  CREATE_INPUT_INVOICE, //10
  UPDATE_INPUT_INVOICE, //11
  DELETE_INPUT_INVOICE, //12

  // Sale Bill
  VIEW_SALE_BILL, //13
  CREATE_SALE_BILL, //14
  UPDATE_SALE_BILL, //15
  DELETE_SALE_BILL, //16

  // EXPENDITURE BILL
  VIEW_EXPENDITURE_BILL, //17
  CREATE_EXPENDITURE_BILL, //18
  UPDATE_EXPENDITURE_BILL, //19
  DELETE_EXPENDITURE_BILL, //20

  // Inventory
  VIEW_INVENTORY, //21
  INVENTORY_BALANCE, //22

  // Sale report
  VIEW_SALE_REPORT, //23
  CREATE_SALE_REPORT, //24
  UPDATE_SALE_REPORT, //25
  DELETE_SALE_REPORT, //26

  ADMIN
}
