name: Build and deploy
on:
  push: 
    branches:
      - develop
jobs: 
  build: 
    name: Build iOS
    runs-on: macos-latest
    steps: 

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get 

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          rubygems: latest
          bundler-cache: true
      - name: Install Fastlane
        run: gem install fastlane

      - name: Create store.json
        run: |
          mkdir -p ios/fastlane
          echo "{
            "key_id": "${{ secrets.KEY_ID }}",
            "issuer_id": "${{ secrets.ISSUER_ID }}",
            "key": "${{ secrets.KEY }}"
          }" > ios/fastlane/store.json

      - name: Install Pod
        run: cd ios && pod install

      - name: Upload to TestFlight
        run: |
          cd ios && fastlane beta
        env: 
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_GIT_BASIC: ${{secrets.MATCH_GIT_BASIC}}
      