name: Build and deploy
on:
  push: 
    branches:
      - develop
jobs: 
  build: 
    name: Build iOS
    runs-on: macos-latest
    steps: 

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get 

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          rubygems: latest
          bundler-cache: true

      - name: Setup Fastlane API Key
        run: |
          echo "key_id=${{ secrets.FASTLANE_KEY_ID }}" >> ~/.fastlane/.env
          echo "issuer_id=${{ secrets.FASTLANE_ISSUER_ID }}" >> ~/.fastlane/.env
          echo "key_filepath=${{ secrets.FASTLANE_KEY_FILEPATH }}" >> ~/.fastlane/.env

      - name: Upload to TestFlight
        env:
          FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_APPLE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_APPLE_KEY_PATH: ${{ secrets.FASTLANE_KEY_FILEPATH }}
        run: |
          fastlane beta
      